### PR TITLE
test if job class responds to #isDisabled in job_list_json

### LINKED ISSUE #551: jenkins_job broken by org.jenkinsci.plugins.workflow.job.WorkflowJob jobs
Jobs of this class cause `job_list_json` to fail as they don't respond to `#isDisabled`.

```
$ /bin/java -jar /usr/lib/jenkins/jenkins-cli.jar -s http://localhost:8080 -i /usr/lib/jenkins/admin_private_key groovy /usr/lib/jenkins/puppet_helper.groovy job_list_json

ERROR: Unexpected exception occurred while performing groovy command.
groovy.lang.MissingMethodException: No signature of method: org.jenkinsci.plugins.workflow.job.WorkflowJob.isDisabled() is applicable for argument types: () values: []
Possible solutions: isBuildable(), isBuildable()
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at hudson.model.AbstractProject$isDisabled.call(Unknown Source)
```

### PR DESCRIPTION
**Pull request by jhoblitt**
Instead of special casing classes which are known not to respond to the
`isDisabled()` method, use introspection.

resolves #551

### CODE REVIEW

File: files/puppet_helper.groovy [hunk 1]
```diff
@@ -947,11 +947,14 @@ class Actions {
     def jobs = util.findJobs(Jenkins.getInstance())
 
     def allInfo = jobs.collect { path, job ->
+      // at least these job classes do not respond to respond to #isDisabled:
+      // - org.jenkinsci.plugins.workflow.job.WorkflowJob
+      // - com.cloudbees.hudson.plugins.folder.Folder
       def enabled = false
-      // folders don't respond to #isDisabled
-      if (job.getClass().getName() != 'com.cloudbees.hudson.plugins.folder.Folder') {
+      if (job.metaClass.respondsTo(job, 'isDisabled')) {
```
Comment (rtyler) [inline files/puppet_helper.groovy]: My first thought, as my eyes focused in on this line: "is this some weird Puppet stuff?" Briefly puzzling to myself "metaClass? respondsTo instead of `respond_to?`? This isn't Ruby!"

Then I looked up and realized this is a Groovy file.


 :coffee: 
 :coffee: 
 :coffee: 
 :coffee: 
 :coffee: 


Carry on

Comment (jhoblitt) [inline files/puppet_helper.groovy]: I'm considering trying to configure vim to warn about a few rubyisms in groovy code.  If I had a dime for every time I've broken a groovy scipt by using `nil` in stead of `null`...
